server:
  port: 9090
#  servlet:
#    #加项目名访问
#    context-path: /wanghui
#xxl:
#  job:
#    admin:
#      addresses: http://localhost:8888/xxl-job-admin
#    executor:
#      ip:
#      port: 9999
#      logpath: /data/applogs/xxl-job/jobhandler
#      appname: demo-job
#    accessToken:

spring:
  application:
    name: wanghui
  resources:
    static-locations: classpath:/static/
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wanghui?characterEncoding=utf8&useUnicode=true&useSSL=false&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: wanghui123
    initialSize: 50
    minIdle: 10
    maxActive: 50
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    hikari:
      maximum-pool-size: 300
      idle-timeout: 0
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      timeout: 100000
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
    #配置rabbitMq 服务器
    rabbitmq:
      host: 127.0.0.1
      port: 15672
      username: guest
      password: guest
      #虚拟host 可以不设置,使用server默认host
      #virtual-host: JCcccHost
    #确认消息已发送到交换机
    publisher-confirms: true
    #确认消息已发送到队列
    publisher-returns: true

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.demo


