server:
  port: 8080
#  servlet:
#    #加项目名访问
#    context-path: /wanghui
spring:
  application:
    name: wanghui
  resources:
    static-locations: classpath:/static

# 数据源配置: Map结构,key为DbName字符串,value为详细配置信息
dataSourceConfigMap:
  mysql_src:
    driverClassName: oracle.jdbc.OracleDriver
    jdbcUrl: jdbc:mysql://172.16.11.96:3306/whsrc?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  mysql_tar:
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://172.16.11.96:3306/whtar?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
# 数据移动配置: List结构
dataSyncConfigList:
  # 表同步: mysql_src（传出） --> mysql_tar（传入）
  - {srcDbName: mysql_src, srcTableName: db_user                ,tarDbName: mysql_tar, tarTableName: db_user                }
